# 配置web端口
server:
  port: 9999
  servlet:
    context-path: /kps
spring:
  # ------------------数据库配置------------------
  datasource:
    url: jdbc:mysql://localhost:3306/kps?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    #   连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
    maximum-pool-size: 100
    #  一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
    idleTimeout: 600000
    # 连接只读数据库时配置为true， 保证安全
    isReadOnly: false
    #   等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
    connectionTimeout: 30000
    #  一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，
    #  参考MySQL wait_timeout参数（show variables like '%timeout%';）
    maxLifetime: 1800000
  # ------------------时间序列化------------------
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    #default-property-inclusion: non_null

# ------------------mybatis配置------------------
mybatis:
  mapper-locations: classpath*:META-INF/mapper/*Mapper.xml  #注意：一定要对应mapper映射xml文件的所在路径
  # mybatis全局配置文件位置
#  config-location: classpath*:/mybatis/config/mybatis-config.xml

# ------------------日志配置------------------
logging:
  level:
    root: info
    # 只打印sql语句
    com.wss.kps.dao: debug
  file:
    name: D:/log/kps.log


